# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Instagram_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 5.0.0'

  # Pods for Instagram_2

end
